spring:
  rabbitmq:
    password: password
    host: localhost
    listener:
      simple:
        prefetch: '100'
        concurrency: '10'
    port: '5672'
    username: admin
  main:
    allow-bean-definition-overriding: 'true'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
  datasource:
    driver-class-name: org.postgresql.Driver
    password: password
    username: user
    url: jdbc:postgresql://localhost:5432/batches
  batch:
    jdbc:
      initialize-schema: always
  application:
    name: spring-batch-template

server:
  port: '8080'


management:
  tracing:
    enabled: true
    sampling:
      probability: 1
    baggage:
      correlation:
        enabled: true
  otlp:
    metrics:
      export:
        enabled: true
#        url: https://otlp-gateway-prod-sa-east-1.grafana.net/otlp/v1/metrics
#        headers:
#          Authorization: ""
    tracing:
      export:
        enabled: true
#      endpoint: https://tempo-prod-17-prod-sa-east-1.grafana.net/tempo
#      headers:
#        Authorization: ""


logging:
  level:
    root: INFO

otel:
  traces:
    exporter: otlp
  exporter:
    otlp:
#      endpoint: https://otlp-gateway-prod-sa-east-1.grafana.net/otlp
#      headers:
#        Authorization: ""
